--Funcion Escalar
-- CREAR ESQUEMA. FN_NOMBREFUNCION
CREATE OR ALTER FUNCTION LFCV.FN_TOTALRESERVAS
(
-- PARAMETRO, TIPO DE DATO
@RESULTADO INT
)
RETURNS INT
AS
BEGIN
	DECLARE @CONTAR INT
	RETURN @CONTAR
END
GO
